import os, glob

replacements = {
    'Lá»—i': 'Lỗi',
    'KhÃ´ng cÃ³': 'Không có',
    'dá»¯ liá»‡u': 'dữ liệu',
    'trÃ¬nh phÃ¡t': 'trình phát',
    'ngoÃ i': 'ngoài',
    'Ná»n': 'Nền',
    'KhÃ´ng': 'Không',
    'thá»ƒ má»Ÿ': 'thể mở',
    'tiáº¿p tá»¥c': 'tiếp tục',
    'trÃªn': 'trên',
    'HÃ£y': 'Hãy',
    'thá»­': 'thử',
    'khÃ¡c': 'khác',
    'chÆ°a': 'chưa',
    'Ä‘Æ°á»£c': 'được',
    'cÃ i Ä‘áº·t': 'cài đặt',
    'hoáº·c': 'hoặc',
    'tÆ°Æ¡ng thÃ­ch': 'tương thích',
    'thiáº¿t bá»‹': 'thiết bị',
    'cá»§a': 'của',
    'báº¡n': 'bạn',
    'Báº¡n': 'Bạn',
    'muá»‘n': 'muốn',
    'nÃ y': 'này',
    'cÃ³ thá»ƒ': 'có thể',
    'gÃ¢y': 'gây',
    'vá»›i': 'với',
    'Chuyá»ƒn': 'Chuyển',
    'sang': 'sang',
    'ná»™i bá»™': 'nội bộ',
    'Tá»‘c Ä‘á»™': 'Tốc độ',
    'phÃ¡t': 'phát',
    'tÃ¬m': 'tìm',
    'tháº¥y': 'thấy',
    'phá»¥ Ä‘á»': 'phụ đề',
    'Phá»¥ Ä‘á»': 'Phụ đề',
    'Ã‚m thanh': 'Âm thanh',
    'káº¿t ná»‘i': 'kết nối',
    'máº¡ng': 'mạng',
    'Ä‘áº¿n': 'đến',
    'Vui lÃ²ng': 'Vui lòng',
    'kiá»ƒm tra': 'kiểm tra',
    'láº¡i': 'lại',
    'tua': 'tua',
    'trong': 'trong',
    'trá»±c tiáº¿p': 'trực tiếp',
    'lÃ¹i': 'lùi',
    'Chá»n': 'Chọn',
    'cÃ³ sáºµn': 'có sẵn',
    'Chá»‰ cÃ³': 'Chỉ có',
    'má»™t': 'một',
    'luá»“ng': 'luồng',
    'Ä‘á»•i': 'đổi',
    'Vá»‹ trÃ­': 'Vị trí',
    'LÃªn': 'Lên',
    'MÃ u': 'Màu',
    'chá»¯': 'chữ',
    'Tráº¯ng': 'Trắng',
    'VÃ ng': 'Vàng',
    'Äá»': 'Đỏ',
    'Xanh lÃ¡': 'Xanh lá',
    'Xanh dÆ°Æ¡ng': 'Xanh dương',
    'Há»“ng': 'Hồng',
    'Xanh lÆ¡': 'Xanh lơ',
    'viá»n': 'viền',
    'Trong suá»‘t': 'Trong suốt',
    'Äen': 'Đen',
    'KhÃ´i phá»¥c': 'Khôi phục',
    'máº·c Ä‘á»‹nh': 'mặc định',
    'Máº·c Ä‘á»‹nh': 'Mặc định',
    'Giá»¯a': 'Giữa',
    'ÄÃ³ng': 'Đóng',
    'Vá»«a': 'Vừa',
    'mÃ n hÃ¬nh': 'màn hình',
    'TrÃ n': 'Tràn',
    'PhÃ³ng to': 'Phóng to',
    'tá»· lá»‡': 'tỷ lệ',
    'Tá»· lá»‡': 'Tỷ lệ',
    'tÃ¹y chá»‰nh': 'tùy chỉnh',
    'Äá»‹nh dáº¡ng': 'Định dạng',
    'há»— trá»£': 'hỗ trợ',
    'cháº¥t lÆ°á»£ng': 'chất lượng',
    'khá»Ÿi táº¡o': 'khởi tạo',
    'Äang': 'Đang',
    'cháº¿ Ä‘á»™': 'chế độ',
    'giáº£i mÃ£': 'giải mã',
    'báº±ng': 'bằng',
    'pháº§n má»m': 'phần mềm',
    'Ä‘Ã£': 'đã',
    'ÄÃ£': 'Đã',
    'bá»‹': 'bị',
    'táº¯t': 'tắt',
    'Táº¯t': 'Tắt',
    'thay tháº¿': 'thay thế',
    'Ä‘áº§y Ä‘á»§': 'đầy đủ',
    'cháº­m': 'chậm',
    'hiá»ƒn thá»‹': 'hiển thị',
    'tháº¥p': 'thấp',
    'hÆ¡n': 'hơn',
    'Táº­p': 'Tập',
    'káº¿t thÃºc': 'kết thúc',
    'theo': 'theo',
    'ThoÃ¡t': 'Thoát',
    'Xuá»‘ng': 'Xuống',
    'Ä‘á»‹nh': 'định',
    'Cá»‘ Ä‘á»‹nh': 'Cố định',
    'chiá»u cao': 'chiều cao',
    'chiá»u rá»™ng': 'chiều rộng',
    'Kiá»ƒm chá»¯': 'Kiểu chữ',
    'Kiá»ƒu chá»¯': 'Kiểu chữ',
    'Dá»‹ch chuyá»ƒn': 'Dịch chuyển',
    'Quay láº¡i': 'Quay lại',
    'Báº­t': 'Bật',
    'Há»§y': 'Hủy',
    'Tá»›i': 'Tới',
    'giá»¯a': 'giữa',
    'tá»«': 'từ',
    'lÆ°u': 'lưu',
    'lá»‹ch sá»­': 'lịch sử',
    'xem': 'xem',
    'Váº¥n Ä‘á»': 'Vấn đề',
    'gá»‘c': 'gốc',
    'tá»± Ä‘á»™ng': 'tự động',
    'mÃ£': 'mã',
    'Tiáº¿ng Viá»‡t': 'Tiếng Việt',
    'viá»‡t': 'việt',
    'chá»¯': 'chữ'
}

for file in glob.glob('app/src/main/java/**/*.java', recursive=True):
    changed = False
    try:
        with open(file, 'r', encoding='utf-8') as f:
            content = f.read()
            
        for k, v in replacements.items():
            if k in content:
                content = content.replace(k, v)
                changed = True
                
        if changed:
            with open(file, 'w', encoding='utf-8') as f:
                f.write(content)
            print('Fixed text in: ' + file)
    except:
        pass
